lzc-sdk-version: "0.1"
name: Walle
package: cloud.lazycat.app.walle
version: 2.0.1
description: 瓦力 Devops开源项目代码部署平台
homepage: https://github.com/meolu/walle-web
author: meolu
application:
  subdomain: walle
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://web.cloud.lazycat.app.walle.lzcapp:80/
services:
  web:
    image: docker.hlmirror.com/alenx/walle-web:2.1
    depends_on:
      - python
  python:
    image: docker.hlmirror.com/alenx/walle-python:2.1
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=walle
      - MYSQL_DATABASE=walle
      - MYSQL_ROOT_PASSWORD=walle
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    command: bash -c "cd /opt/walle_home/ && /bin/bash admin.sh migration &&  python
      waller.py"
    depends_on:
      - db
    binds:
      - /lzcapp/var/plugins:/opt/walle_home/plugins/
      - /lzcapp/var/codebase:/opt/walle_home/codebase/
      - /lzcapp/var/logs:/opt/walle_home/logs/
      - /lzcapp/var/.ssh:/root/.ssh/
  db:
    image: registry.lazycat.cloud/mysql
    environment:
      - MYSQL_PASSWORD=walle
      - MYSQL_DATABASE=walle
      - MYSQL_ROOT_PASSWORD=walle
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    binds:
      - /lzcapp/var/db:/var/lib/mysql
    health_check:
      test:
        - CMD-SHELL
        - mysqladmin ping -h db -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 90s